const script = String.raw`(() => {
  const scriptTag = document.currentScript;
  const key = scriptTag && scriptTag.dataset.tenant;
  if (!key || document.getElementById('gavrion-chat-root')) return;
  const api = new URL(scriptTag.src).origin;
  const visitorStorage = 'gavrion_visitor_' + key;
  const conversationStorage = 'gavrion_conversation_' + key;
  let visitorId = localStorage.getItem(visitorStorage);
  if (!visitorId) { visitorId = crypto.randomUUID ? crypto.randomUUID() : Date.now() + '-' + Math.random().toString(36).slice(2); localStorage.setItem(visitorStorage, visitorId); }
  let conversationId = localStorage.getItem(conversationStorage) || '';
  let config = { company: 'Chat', welcome: 'Hola, ¿cómo podemos ayudarte?', color: '#087f69', logoUrl: '' };
  const host = document.createElement('div'); host.id = 'gavrion-chat-root'; host.style.color = '#1f2925'; document.body.appendChild(host);
  const root = host.attachShadow({ mode: 'open' });
  root.innerHTML = '<style>*{box-sizing:border-box;font-family:Arial,sans-serif}.button{position:fixed;right:22px;bottom:22px;width:58px;height:58px;border:0;border-radius:50%;background:var(--brand);color:#fff;font-size:25px;box-shadow:0 8px 28px #0003;cursor:pointer;z-index:2147483647}.panel{position:fixed;right:22px;bottom:92px;width:min(360px,calc(100vw - 28px));height:520px;max-height:calc(100vh - 120px);background:#fff;border-radius:18px;box-shadow:0 18px 60px #0004;overflow:hidden;display:none;flex-direction:column;z-index:2147483647}.panel.open{display:flex}.head{padding:16px;background:var(--brand);color:#fff;display:flex;align-items:center;gap:10px}.head img,.logo{width:38px;height:38px;border-radius:10px;background:#fff;object-fit:contain;padding:3px}.head strong{display:block}.head small{opacity:.85}.close{margin-left:auto;border:0;background:transparent;color:#fff;font-size:22px;cursor:pointer}.messages{flex:1;overflow:auto;background:#f5f7f6;padding:14px;display:flex;flex-direction:column;gap:9px}.msg{max-width:82%;padding:10px 12px;border-radius:13px;font-size:14px;line-height:1.35}.in{background:#fff;border:1px solid #e4e8e6}.out{align-self:flex-end;background:color-mix(in srgb,var(--brand) 15%,white)}.identity{display:grid;gap:8px;padding:12px;border-top:1px solid #e8ecea}.identity input,.compose input{border:1px solid #dfe5e2;border-radius:10px;padding:10px;outline:none}.compose{display:flex;gap:7px;padding:11px;border-top:1px solid #e8ecea}.compose input{flex:1}.send{border:0;border-radius:10px;background:var(--brand);color:#fff;padding:0 15px;font-weight:bold;cursor:pointer}.error{color:#a9363e;font-size:12px;padding:0 12px 8px}</style><button class="button" aria-label="Abrir chat">✦</button><section class="panel" aria-label="Chat"><header class="head"><span class="logo"></span><div><strong class="company">Chat</strong><small>Normalmente respondemos pronto</small></div><button class="close" aria-label="Cerrar">×</button></header><div class="messages"></div><div class="identity"><input class="name" maxlength="100" placeholder="Tu nombre"><input class="email" type="email" maxlength="254" placeholder="Tu correo (opcional)"></div><form class="compose"><input class="text" maxlength="2000" placeholder="Escribe tu mensaje..." required><button class="send">Enviar</button></form><div class="error"></div></section>';
  const panel=root.querySelector('.panel'), messages=root.querySelector('.messages'), error=root.querySelector('.error');
  const add=(text,direction,id)=>{ if(id && root.getElementById(id)) return; const el=document.createElement('div'); if(id) el.id=id; el.className='msg '+(direction==='outbound'?'in':'out'); el.textContent=text; messages.appendChild(el); messages.scrollTop=messages.scrollHeight; };
  fetch(api+'/api/widget/config?key='+encodeURIComponent(key)).then(r=>r.json()).then(data=>{ if(data.error) throw Error(data.error); config=data; host.style.setProperty('--brand',config.color); root.querySelector('.company').textContent=config.company; const logo=root.querySelector('.logo'); if(config.logoUrl){ const img=document.createElement('img'); img.src=config.logoUrl; img.alt=''; logo.replaceWith(img); } else logo.textContent=config.company.charAt(0).toUpperCase(); if(!conversationId)add(config.welcome,'outbound','welcome'); }).catch(e=>{error.textContent=e.message});
  root.querySelector('.button').onclick=()=>panel.classList.toggle('open'); root.querySelector('.close').onclick=()=>panel.classList.remove('open');
  const refresh=()=>{ if(!conversationId)return; fetch(api+'/api/widget/messages?key='+encodeURIComponent(key)+'&visitorId='+encodeURIComponent(visitorId)+'&conversationId='+encodeURIComponent(conversationId)).then(r=>r.json()).then(data=>(data.messages||[]).forEach(m=>add(m.body,m.direction,'m-'+m.id))).catch(()=>{}); };
  root.querySelector('.compose').onsubmit=async e=>{ e.preventDefault(); error.textContent=''; const text=root.querySelector('.text'), send=root.querySelector('.send'); if(send.disabled)return; const messageText=text.value.trim(); if(!messageText)return; const pendingId='pending-'+Date.now(); add(messageText,'inbound',pendingId); text.value=''; send.disabled=true; send.textContent='Enviando…'; try{ const response=await fetch(api+'/api/widget/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key,visitorId,name:root.querySelector('.name').value,email:root.querySelector('.email').value,text:messageText})}); const data=await response.json(); if(!response.ok)throw Error(data.error||'No se pudo enviar'); root.getElementById(pendingId)?.remove(); conversationId=data.conversationId; localStorage.setItem(conversationStorage,conversationId); add(data.message.body,data.message.direction,'m-'+data.message.id); if(data.botMessage)add(data.botMessage.body,data.botMessage.direction,'m-'+data.botMessage.id); root.querySelector('.identity').style.display='none'; }catch(e){ root.getElementById(pendingId)?.remove(); text.value=messageText; error.textContent=e.message; }finally{send.disabled=false;send.textContent='Enviar';text.focus()} };
  if(conversationId){ root.querySelector('.identity').style.display='none'; refresh(); } setInterval(refresh,5000);
})();`;

export function GET() {
  return new Response(script, { headers: { "Content-Type": "application/javascript; charset=utf-8", "Cache-Control": "public, max-age=300", "Access-Control-Allow-Origin": "*" } });
}
