import { NextResponse } from "next/server";
import { createServerSupabase } from "@/lib/supabase/server";

async function context(requireAdmin=false){const supabase=await createServerSupabase();const{data:auth}=await supabase.auth.getUser();if(!auth.user)return null;const{data:membership}=await supabase.from("memberships").select("tenant_id, role").eq("user_id",auth.user.id).limit(1).maybeSingle();if(!membership||(requireAdmin&&!["owner","admin"].includes(membership.role)))return null;return{supabase,membership};}
export async function GET(){const ctx=await context();if(!ctx)return NextResponse.json({error:"No autorizado"},{status:403});const[tenant,profile]=await Promise.all([ctx.supabase.from("tenants").select("id, name, logo_url, custom_domain, settings").eq("id",ctx.membership.tenant_id).single(),ctx.supabase.from("company_profiles").select("*").eq("tenant_id",ctx.membership.tenant_id).maybeSingle()]);if(tenant.error)return NextResponse.json({error:tenant.error.message},{status:400});return NextResponse.json({tenant:tenant.data,profile:profile.data||{}});}
export async function PATCH(request:Request){const ctx=await context(true);if(!ctx)return NextResponse.json({error:"Solo administradores"},{status:403});const body=await request.json();const color=String(body.widgetColor||"#087f69");if(!/^#[0-9a-f]{6}$/i.test(color))return NextResponse.json({error:"Color hexadecimal inválido"},{status:400});const domain=String(body.customDomain||"").trim().toLowerCase().replace(/^https?:\/\//,"").replace(/\/$/,"");if(domain&&!/^[a-z0-9.-]+\.[a-z]{2,}$/i.test(domain))return NextResponse.json({error:"Dominio inválido"},{status:400});if(body.responsibleUserId){const{data:member}=await ctx.supabase.from("memberships").select("user_id").eq("tenant_id",ctx.membership.tenant_id).eq("user_id",body.responsibleUserId).maybeSingle();if(!member)return NextResponse.json({error:"Responsable inválido"},{status:400});}
  const{data:current}=await ctx.supabase.from("tenants").select("settings").eq("id",ctx.membership.tenant_id).single();const settings={...(current?.settings||{}),widget_color:color,widget_welcome:String(body.widgetWelcome||"").slice(0,300),widget_status_message:String(body.widgetStatusMessage||"").slice(0,120),widget_offline_message:String(body.widgetOfflineMessage||"").slice(0,300),widget_position:body.widgetPosition==="left"?"left":"right",widget_launcher:String(body.widgetLauncher||"✦").slice(0,4)};
  const tenant=await ctx.supabase.from("tenants").update({name:String(body.companyName||"").trim(),logo_url:body.logoUrl||null,custom_domain:domain||null,settings}).eq("id",ctx.membership.tenant_id);if(tenant.error)return NextResponse.json({error:tenant.error.message},{status:400});
  const profile=await ctx.supabase.from("company_profiles").upsert({tenant_id:ctx.membership.tenant_id,legal_name:body.legalName||null,tax_id:body.taxId||null,legal_address:body.legalAddress||null,phone:body.phone||null,public_email:body.publicEmail||null,website:body.website||null,timezone:body.timezone||"America/Tegucigalpa",business_hours:body.businessHours||{},responsible_user_id:body.responsibleUserId||null},{onConflict:"tenant_id"});return profile.error?NextResponse.json({error:profile.error.message},{status:400}):NextResponse.json({ok:true});}

