"use client";

import { useEffect, useMemo, useState } from "react";
import type { GastronomySiteConfig, MenuItem } from "@/lib/site-builder";
import "./site-editor.css";

type Project={id:string;name:string;slug:string;status:string;configuration:GastronomySiteConfig;tenant?:{name:string}|null};
type Tab="design"|"content"|"menu"|"integrations";

export default function SiteEditor({id}:{id:string}){
  const [project,setProject]=useState<Project|null>(null);const [config,setConfig]=useState<GastronomySiteConfig|null>(null);
  const [tab,setTab]=useState<Tab>("design");const [device,setDevice]=useState<"desktop"|"tablet"|"mobile">("desktop");
  const [assets,setAssets]=useState({html:"",css:"",js:""});const [notice,setNotice]=useState("");const [saving,setSaving]=useState(false);
  useEffect(()=>{Promise.all([fetch("/api/admin/sites",{cache:"no-store"}).then(r=>r.json()),fetch("/templates/gastronomia-a/index.html").then(r=>r.text()),fetch("/templates/gastronomia-a/styles.css").then(r=>r.text()),fetch("/templates/gastronomia-a/app.js").then(r=>r.text())]).then(([projects,html,css,js])=>{const found=(projects as Project[]).find(item=>item.id===id);if(!found)throw new Error("No se encontró el proyecto.");setProject(found);setConfig(found.configuration);setAssets({html,css,js})}).catch(error=>setNotice(error.message))},[id]);
  const preview=useMemo(()=>{if(!config||!assets.html)return"";const safe=JSON.stringify(config).replace(/<\//g,"<\\/");return assets.html.replace(/<link[^>]*styles\.css[^>]*>/i,`<style>${assets.css}</style>`).replace(/<script[^>]*site-config\.js[^>]*><\/script>/i,"").replace(/<script[^>]*app\.js[^>]*><\/script>/i,`<script>window.GAVRION_SITE=${safe};</script><script>${assets.js}</script>`)},[config,assets]);
  function set(path:string,value:unknown){setConfig(current=>{if(!current)return current;const next=structuredClone(current) as Record<string,unknown>;const parts=path.split(".");let target=next;for(const key of parts.slice(0,-1))target=target[key] as Record<string,unknown>;target[parts.at(-1)!]=value;return next as unknown as GastronomySiteConfig})}
  function updateItem(index:number,patch:Partial<MenuItem>){setConfig(current=>current?{...current,menu:{...current.menu,items:current.menu.items.map((item,i)=>i===index?{...item,...patch}:item)}}:current)}
  function addItem(){setConfig(current=>current?{...current,menu:{...current.menu,items:[...current.menu.items,{id:crypto.randomUUID(),category:current.menu.categories[0]||"Menú",name:"Nuevo platillo",description:"Descripción del platillo",price:0,imageUrl:"",active:true}]}}:current)}
  async function save(){if(!project||!config)return;setSaving(true);setNotice("");try{const response=await fetch("/api/admin/sites",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:project.id,name:project.name,status:project.status,configuration:config})});const data=await response.json();if(!response.ok)throw new Error(data.error||"No fue posible guardar.");setProject({...project,...data});setNotice("Cambios guardados en Supabase.")}catch(error){setNotice(error instanceof Error?error.message:"No fue posible guardar.")}finally{setSaving(false)}}
  if(!project||!config)return <main className="site-editor-loading">{notice||"Cargando editor…"}</main>;
  return <main className="site-editor-shell">
    <header><div><a href="/admin">← Proyectos</a><p>EDITOR DE SITIO · GASTRONOMÍA A</p><h1>{project.name}</h1></div><div className="editor-actions"><select value={project.status} onChange={event=>setProject({...project,status:event.target.value})}><option value="draft">Borrador</option><option value="review">En revisión</option><option value="ready">Listo</option><option value="exported">Exportado</option></select><button onClick={()=>void save()} disabled={saving}>{saving?"Guardando…":"Guardar"}</button><a href={`/api/admin/sites/${id}/export`}>Generar proyecto ↓</a></div></header>
    {notice&&<div className="editor-notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
    <div className="site-editor-workspace"><aside><nav>{([["design","Diseño"],["content","Contenido"],["menu","Menú"],["integrations","CRM y chatbox"]] as [Tab,string][]).map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}>{label}</button>)}</nav>
      {tab==="design"&&<section><h2>Identidad visual</h2><Field label="Nombre" value={config.brand.name} onChange={v=>set("brand.name",v)}/><Field label="Nombre corto" value={config.brand.shortName} onChange={v=>set("brand.shortName",v)}/><Field label="URL del logo" value={config.brand.logoUrl} onChange={v=>set("brand.logoUrl",v)}/><Field label="Imagen principal" value={config.hero.imageUrl} onChange={v=>set("hero.imageUrl",v)}/><Color label="Color principal" value={config.brand.primaryColor} onChange={v=>set("brand.primaryColor",v)}/><Color label="Color secundario" value={config.brand.secondaryColor} onChange={v=>set("brand.secondaryColor",v)}/><Color label="Fondo" value={config.brand.backgroundColor} onChange={v=>set("brand.backgroundColor",v)}/></section>}
      {tab==="content"&&<section><h2>Textos y contacto</h2><Field label="Frase superior" value={config.hero.eyebrow} onChange={v=>set("hero.eyebrow",v)}/><Field label="Título principal" value={config.hero.title} onChange={v=>set("hero.title",v)}/><Area label="Descripción" value={config.hero.description} onChange={v=>set("hero.description",v)}/><Field label="Teléfono" value={config.contact.phone} onChange={v=>set("contact.phone",v)}/><Field label="WhatsApp" value={config.contact.whatsapp} onChange={v=>set("contact.whatsapp",v)}/><Field label="Correo" value={config.contact.email} onChange={v=>set("contact.email",v)}/><Field label="Dirección" value={config.contact.address} onChange={v=>set("contact.address",v)}/><Field label="Horario" value={config.contact.schedule} onChange={v=>set("contact.schedule",v)}/></section>}
      {tab==="menu"&&<section><div className="editor-section-title"><h2>Menú</h2><button onClick={addItem}>＋ Platillo</button></div><Field label="Categorías (separadas por coma)" value={config.menu.categories.join(", ")} onChange={v=>set("menu.categories",v.split(",").map(x=>x.trim()).filter(Boolean))}/>{config.menu.items.map((item,index)=><article className="menu-editor-item" key={item.id}><Field label="Nombre" value={item.name} onChange={v=>updateItem(index,{name:v})}/><Field label="Categoría" value={item.category} onChange={v=>updateItem(index,{category:v})}/><Field label="Precio" type="number" value={String(item.price)} onChange={v=>updateItem(index,{price:Number(v)})}/><Field label="Imagen" value={item.imageUrl} onChange={v=>updateItem(index,{imageUrl:v})}/><Area label="Descripción" value={item.description} onChange={v=>updateItem(index,{description:v})}/><div className="menu-item-actions"><label><input type="checkbox" checked={item.active} onChange={e=>updateItem(index,{active:e.target.checked})}/> Visible</label><button onClick={()=>set("menu.items",config.menu.items.filter((_,i)=>i!==index))}>Eliminar</button></div></article>)}</section>}
      {tab==="integrations"&&<section><h2>CRM y chatbox</h2><p className="editor-help">La empresa queda vinculada mediante su identificador público. Las claves privadas nunca se agregan al sitio.</p><Field label="URL del CRM" value={config.integrations.crmBaseUrl} onChange={v=>set("integrations.crmBaseUrl",v)}/><Field label="Identificador del chatbox" value={config.integrations.tenantKey} onChange={v=>set("integrations.tenantKey",v)}/><label className="editor-check"><input type="checkbox" checked={config.integrations.useRealChatbox} onChange={e=>set("integrations.useRealChatbox",e.target.checked)}/> Usar chatbox real</label><h3>Funciones</h3>{Object.entries(config.features).map(([key,value])=><label className="editor-check" key={key}><input type="checkbox" checked={value} onChange={e=>set(`features.${key}`,e.target.checked)}/>{({orders:"Pedidos",reservations:"Reservaciones",tableQr:"Menú QR",kitchenPreview:"Vista de cocina"} as Record<string,string>)[key]}</label>)}</section>}
    </aside><section className="preview-panel"><div className="preview-toolbar"><span>Vista previa</span><div><button className={device==="desktop"?"active":""} onClick={()=>setDevice("desktop")}>Escritorio</button><button className={device==="tablet"?"active":""} onClick={()=>setDevice("tablet")}>Tablet</button><button className={device==="mobile"?"active":""} onClick={()=>setDevice("mobile")}>Móvil</button></div></div><div className={`preview-stage ${device}`}><iframe title="Vista previa del sitio" srcDoc={preview}/></div></section></div>
  </main>
}

function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <label className="editor-field">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Area({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="editor-field">{label}<textarea value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Color({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="editor-field">{label}<span className="editor-color"><input type="color" value={value} onChange={e=>onChange(e.target.value)}/><input value={value} onChange={e=>onChange(e.target.value)}/></span></label>}
