"use client";
import { FormEvent,useEffect,useState } from "react";
import { createClientSupabase } from "@/lib/supabase/client";

type Pipeline={id:string;name:string;is_default:boolean;active:boolean};
type Stage={id:string;pipeline_id:string;name:string;stage_key:string;color:string;position:number;probability:number;is_won:boolean;is_lost:boolean};
type Deal={id:string;title:string;value:number;stage_id:string|null;stage:string;contact_id:string|null;owner_id:string|null;expected_close_date:string|null;contacts?:{full_name?:string}|null};
type Contact={id:string;name:string};

export function PipelineWorkspace({tenantId,contacts,userId,canConfigure}:{tenantId:string;contacts:Contact[];userId:string;canConfigure:boolean}){
 const [pipelines,setPipelines]=useState<Pipeline[]>([]),[pipelineId,setPipelineId]=useState(""),[stages,setStages]=useState<Stage[]>([]),[deals,setDeals]=useState<Deal[]>([]),[configure,setConfigure]=useState(false),[notice,setNotice]=useState("");
 const [pipelineName,setPipelineName]=useState(""),[dealOpen,setDealOpen]=useState(false),[dealTitle,setDealTitle]=useState(""),[dealValue,setDealValue]=useState(""),[contactId,setContactId]=useState("");
 async function load(){const s=createClientSupabase();if(!s)return;const p=await s.from("pipelines").select("id,name,is_default,active").eq("tenant_id",tenantId).eq("active",true).order("created_at");const list=(p.data||[]) as Pipeline[];setPipelines(list);setPipelineId(x=>x||list.find(v=>v.is_default)?.id||list[0]?.id||"");}
 useEffect(()=>{void load()},[tenantId]);
 useEffect(()=>{if(!pipelineId)return;const s=createClientSupabase();if(!s)return;Promise.all([s.from("pipeline_stages").select("*").eq("pipeline_id",pipelineId).order("position"),s.from("deals").select("id,title,value,stage_id,stage,contact_id,owner_id,expected_close_date,contacts(full_name)").eq("tenant_id",tenantId).eq("pipeline_id",pipelineId).order("created_at",{ascending:false})]).then(([a,b])=>{setStages((a.data||[]) as Stage[]);setDeals((b.data||[]) as unknown as Deal[]);if(a.error||b.error)setNotice(a.error?.message||b.error?.message||"")})},[pipelineId,tenantId]);
 async function addPipeline(e:FormEvent){e.preventDefault();if(!pipelineName.trim())return;const s=createClientSupabase();if(!s)return;const created=await s.from("pipelines").insert({tenant_id:tenantId,name:pipelineName.trim(),is_default:pipelines.length===0}).select().single();if(created.error){setNotice(created.error.message);return}const p=created.data as Pipeline;const defaults=[["Nuevo","new","#514bb7",10],["Propuesta","proposal","#2f80ed",40],["Ganado","won","#219653",100]];await s.from("pipeline_stages").insert(defaults.map((x,i)=>({tenant_id:tenantId,pipeline_id:p.id,name:x[0],stage_key:x[1],color:x[2],position:i,probability:x[3],is_won:x[1]==="won"})));setPipelineName("");await load();setPipelineId(p.id)}
 async function addStage(){const name=window.prompt("Nombre de la nueva etapa:")?.trim();if(!name)return;const s=createClientSupabase();if(!s)return;const stage_key=`stage_${Date.now()}`;const result=await s.from("pipeline_stages").insert({tenant_id:tenantId,pipeline_id: pipelineId,name,stage_key,color:"#7c74d8",position:stages.length,probability:50}).select().single();if(result.error)setNotice(result.error.message);else setStages(x=>[...x,result.data as Stage])}
 async function saveStage(stage:Stage,changes:Partial<Stage>){const next={...stage,...changes};setStages(x=>x.map(v=>v.id===stage.id?next:v));const s=createClientSupabase();if(!s)return;const result=await s.from("pipeline_stages").update(changes).eq("id",stage.id).eq("tenant_id",tenantId);if(result.error){setNotice(result.error.message);setStages(x=>x.map(v=>v.id===stage.id?stage:v))}}
 async function removeStage(stage:Stage){if(deals.some(d=>d.stage_id===stage.id)){setNotice("Mueve primero las oportunidades de esta etapa.");return}if(!confirm(`¿Eliminar la etapa ${stage.name}?`))return;const s=createClientSupabase();if(!s)return;const r=await s.from("pipeline_stages").delete().eq("id",stage.id);if(r.error)setNotice(r.error.message);else setStages(x=>x.filter(v=>v.id!==stage.id))}
 async function createDeal(e:FormEvent){e.preventDefault();const value=Number(dealValue);if(!dealTitle.trim()||!Number.isFinite(value)||!stages[0])return;const s=createClientSupabase();if(!s)return;const stage=stages[0];const r=await s.from("deals").insert({tenant_id:tenantId,pipeline_id:pipelineId,stage_id:stage.id,stage:stage.stage_key,title:dealTitle.trim(),value,currency:"HNL",contact_id:contactId||null,owner_id:userId||null}).select("id,title,value,stage_id,stage,contact_id,owner_id,expected_close_date,contacts(full_name)").single();if(r.error)setNotice(r.error.message);else{setDeals(x=>[r.data as unknown as Deal,...x]);setDealOpen(false);setDealTitle("");setDealValue("")}}
 async function move(deal:Deal,target:Stage){const old=deal;setDeals(x=>x.map(d=>d.id===deal.id?{...d,stage_id:target.id,stage:target.stage_key}:d));const s=createClientSupabase();if(!s)return;const r=await s.from("deals").update({stage_id:target.id,stage:target.stage_key}).eq("id",deal.id).eq("tenant_id",tenantId);if(r.error){setNotice(r.error.message);setDeals(x=>x.map(d=>d.id===deal.id?old:d))}}
 return <section className="view active"><div className="section-heading"><div><h2>Pipeline comercial</h2><p>Configura procesos, etapas, colores y probabilidades por empresa.</p></div><div className="heading-actions"><button className="ghost-button" onClick={()=>setConfigure(!configure)}>{configure?"Cerrar configuración":"Configurar pipelines"}</button><button className="primary-button" onClick={()=>setDealOpen(true)}>＋ Nueva oportunidad</button></div></div>{notice&&<div className="module-error">{notice}<button onClick={()=>setNotice("")}>×</button></div>}<div className="pipeline-selector"><label>Pipeline<select className="select" value={pipelineId} onChange={e=>setPipelineId(e.target.value)}>{pipelines.map(p=><option key={p.id} value={p.id}>{p.name}{p.is_default?" · Principal":""}</option>)}</select></label></div>
 {configure&&canConfigure&&<article className="panel pipeline-config"><form onSubmit={addPipeline}><input value={pipelineName} onChange={e=>setPipelineName(e.target.value)} placeholder="Nombre del nuevo pipeline"/><button className="primary-button">Crear pipeline</button></form><div className="stage-editor">{stages.map((stage,index)=><div key={stage.id}><input aria-label="Color" type="color" value={stage.color} onChange={e=>void saveStage(stage,{color:e.target.value})}/><input value={stage.name} onChange={e=>setStages(x=>x.map(v=>v.id===stage.id?{...v,name:e.target.value}:v))} onBlur={e=>void saveStage(stage,{name:e.target.value.trim()||stage.name})}/><label>Probabilidad <input type="number" min="0" max="100" value={stage.probability} onChange={e=>void saveStage(stage,{probability:Number(e.target.value)})}/>%</label><button disabled={index===0} onClick={()=>void saveStage(stage,{position:index-1})}>↑</button><button className="danger-button" onClick={()=>void removeStage(stage)}>Eliminar</button></div>)}</div><button className="ghost-button" onClick={()=>void addStage()}>＋ Añadir etapa</button></article>}
 {dealOpen&&<form className="inline-create deal-create" onSubmit={createDeal}><input autoFocus required value={dealTitle} onChange={e=>setDealTitle(e.target.value)} placeholder="Título"/><select className="select" value={contactId} onChange={e=>setContactId(e.target.value)}><option value="">Sin contacto</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input required type="number" min="0" value={dealValue} onChange={e=>setDealValue(e.target.value)} placeholder="Valor HNL"/><button className="primary-button">Guardar</button><button type="button" className="ghost-button" onClick={()=>setDealOpen(false)}>Cancelar</button></form>}
 <div className="kanban">{stages.map((stage,index)=><div className="kanban-column" key={stage.id} style={{borderTop:`4px solid ${stage.color}`}}><div className="kanban-title">{stage.name}<span>{deals.filter(d=>d.stage_id===stage.id).length}</span><small>{stage.probability}%</small></div>{deals.filter(d=>d.stage_id===stage.id).map(deal=><article className="deal-card" key={deal.id}><h4>{deal.title}</h4><p>{deal.contacts?.full_name||"Sin contacto"}</p><div className="deal-footer"><strong>{new Intl.NumberFormat("es-HN",{style:"currency",currency:"HNL",maximumFractionDigits:0}).format(deal.value)}</strong>{index<stages.length-1&&<button className="ghost-button" onClick={()=>void move(deal,stages[index+1])}>Avanzar →</button>}</div></article>)}</div>)}</div></section>
}
