"use client";
import { useEffect, useState } from "react";

type Report = { metrics:{conversations:number;contacts:number;conversion:number;averageResponseMinutes:number;wonDeals:number;salesValue:number};channels:{name:string;value:number}[];daily:{date:string;conversations:number;contacts:number}[];agents:{id:string;replies:number}[] };
export function ReportsView() {
  const [period,setPeriod]=useState("30d"); const [data,setData]=useState<Report|null>(null); const [error,setError]=useState("");
  useEffect(()=>{setError("");fetch(`/api/reports?period=${period}`).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error);setData(body)}).catch(e=>setError(e.message))},[period]);
  const max=Math.max(...(data?.daily.map(item=>item.conversations+item.contacts)||[1]),1);
  return <section className="view active"><div className="section-heading"><div><h2>Reportes reales</h2><p>Conversión, atención, ventas, canales y rendimiento del periodo.</p></div><select className="select" value={period} onChange={e=>setPeriod(e.target.value)}><option value="7d">7 días</option><option value="30d">30 días</option><option value="90d">90 días</option></select></div>{error&&<div className="auth-message error">{error}</div>}{!data?<div className="panel report-loading">Calculando indicadores…</div>:<><div className="metrics-grid report-metrics">{[["Conversaciones",data.metrics.conversations.toLocaleString("es-HN")],["Conversión",`${data.metrics.conversion.toFixed(1)}%`],["Respuesta promedio",data.metrics.averageResponseMinutes<1?"< 1 min":`${data.metrics.averageResponseMinutes.toFixed(1)} min`],["Ventas ganadas",data.metrics.wonDeals.toLocaleString("es-HN")],["Valor vendido",new Intl.NumberFormat("es-HN",{style:"currency",currency:"HNL",maximumFractionDigits:0}).format(data.metrics.salesValue)],["Contactos nuevos",data.metrics.contacts.toLocaleString("es-HN")]].map(([label,value])=><article className="metric-card" key={label}><span>{label}</span><strong>{value}</strong><small>Datos reales del periodo</small></article>)}</div><div className="reports-layout"><article className="panel"><div className="panel-header"><div><h3>Actividad diaria</h3><p>Conversaciones y contactos</p></div></div><div className="report-chart">{data.daily.map(item=><div className="report-bar-wrap" key={item.date}><span className="report-bar" style={{height:`${Math.max(4,(item.conversations+item.contacts)/max*100)}%`}} title={`${item.conversations} conversaciones · ${item.contacts} contactos`}/><small>{new Date(`${item.date}T00:00:00`).toLocaleDateString("es-HN",{day:"2-digit",month:"2-digit"})}</small></div>)}</div></article><article className="panel"><div className="panel-header"><div><h3>Canales</h3><p>Distribución de conversaciones</p></div></div><div className="channel-report">{data.channels.length?data.channels.map(channel=><div key={channel.name}><span>{channel.name}</span><strong>{channel.value}</strong></div>):<p className="table-empty">Sin conversaciones en el periodo.</p>}</div><div className="panel-header agent-heading"><div><h3>Rendimiento del equipo</h3><p>Respuestas enviadas por agente</p></div></div><div className="channel-report">{data.agents.length?data.agents.map((agent,index)=><div key={agent.id}><span>Agente {index+1}</span><strong>{agent.replies}</strong></div>):<p className="table-empty">Todavía no hay respuestas humanas.</p>}</div></article></div></>}</section>;
}

