"use client";

import {useEffect,useMemo,useState} from "react";
import {sanitizeSiteConfig,type GastronomySiteConfig} from "@/lib/site-builder";
import "./site-review.css";

type Project={id:string;tenant_id:string;template_key:string;name:string;slug:string;status:string;configuration:GastronomySiteConfig;review_note:string|null;reviewed_at:string|null;updated_at:string;tenant?:{id:string;name:string}|null};
type Version={id:string;version:number;configuration:GastronomySiteConfig;created_at:string;created_by:string|null};
type ReviewResponse={project:Project;versions:Version[];canReview:boolean};
const statusLabels:Record<string,string>={draft:"Borrador",review:"En revisión",ready:"Aprobado / listo para publicar",exported:"Exportado"};
const configLabels:Record<string,string>={brand:"Identidad visual",seo:"SEO",hero:"Portada",experience:"Experiencia",menu:"Menú",properties:"Catálogo inmobiliario",contact:"Contacto",social:"Redes sociales",gallery:"Galería",features:"Funciones",integrations:"CRM y chatbox",template:"Plantilla"};

function changedSections(current:GastronomySiteConfig,previous?:GastronomySiteConfig){
  if(!previous)return Object.keys(configLabels).map(key=>configLabels[key]||key);
  return Object.keys(configLabels).filter(key=>JSON.stringify((current as unknown as Record<string,unknown>)[key])!==JSON.stringify((previous as unknown as Record<string,unknown>)[key])).map(key=>configLabels[key]||key);
}

export default function SiteReviewPage({params}:{params:Promise<{id:string}>}){
  const [id,setId]=useState("");const [data,setData]=useState<ReviewResponse|null>(null);const [assets,setAssets]=useState({html:"",css:"",js:""});const [notice,setNotice]=useState("");const [reviewNote,setReviewNote]=useState("");const [saving,setSaving]=useState(false);
  useEffect(()=>{void Promise.resolve(params).then(value=>setId(value.id))},[params]);
  useEffect(()=>{if(!id)return;(async()=>{try{const response=await fetch(`/api/admin/sites/${id}/review`,{cache:"no-store"});const value=await response.json();if(!response.ok)throw new Error(value.error||"No se pudo cargar la revisión.");const templateDir=value.project?.template_key==="inmobiliaria-a"?"inmobiliaria-a":"gastronomia-a";const [htmlResponse,cssResponse,jsResponse]=await Promise.all([fetch(`/templates/${templateDir}/index.html`),fetch(`/templates/${templateDir}/styles.css`),fetch(`/templates/${templateDir}/app.js`)]);if(!htmlResponse.ok||!cssResponse.ok||!jsResponse.ok)throw new Error(`No se encontraron los archivos de la plantilla ${templateDir}.`);const [html,css,js]=await Promise.all([htmlResponse.text(),cssResponse.text(),jsResponse.text()]);setData(value as ReviewResponse);setReviewNote(value.project.review_note||"");setAssets({html,css,js})}catch(error){setNotice(error instanceof Error?error.message:"No se pudo cargar la revisión.")}})()},[id]);
  const preview=useMemo(()=>{if(!data||!assets.html)return"";const safe=JSON.stringify(sanitizeSiteConfig(data.project.configuration)).replace(/<\//g,"<\\/");return assets.html.replace(/<link[^>]*styles\.css[^>]*>/i,`<style>${assets.css}</style>`).replace(/<script[^>]*site-config\.js[^>]*><\/script>/i,"").replace(/<script[^>]*app\.js[^>]*><\/script>/i,`<script>window.GAVRION_SITE=${safe};</script><script>${assets.js}</script>`)},[assets,data]);
  const previous=data?.versions?.[1]?.configuration;
  const changed=useMemo(()=>data?changedSections(data.project.configuration,previous):[],[data,previous]);
  async function review(action:"approve"|"reject"){if(!data||saving)return;if(action==="reject"&&!reviewNote.trim()){setNotice("Escribe una observación antes de devolver el sitio.");return}setSaving(true);setNotice("");try{const response=await fetch(`/api/admin/sites/${data.project.id}/review`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,reviewNote})});const value=await response.json();if(!response.ok)throw new Error(value.error||"No se pudo actualizar la revisión.");setData(current=>current?{...current,project:{...current.project,...value}}:current);setNotice(action==="approve"?"Sitio aprobado y listo para publicar.":"Sitio devuelto al vendedor con observaciones.")}catch(error){setNotice(error instanceof Error?error.message:"No se pudo actualizar la revisión.")}finally{setSaving(false)}}
  if(!data)return <main className="site-review-loading"><strong>{notice||"Cargando revisión del sitio…"}</strong>{notice&&<a href="/admin">← Volver a Sitios web</a>}</main>;
  return <main className="site-review-shell"><header><div><a href="/admin">← Sitios web</a><p>REVISIÓN DE SITIO · {data.project.template_key}</p><h1>{data.project.name}</h1><small>{data.project.tenant?.name||"Empresa"}</small></div><div className="site-review-header-actions"><span className={`site-status ${data.project.status}`}>{statusLabels[data.project.status]||data.project.status}</span><a className="site-review-editor-link" href={`/admin/sites/${data.project.id}`}>Abrir editor</a></div></header>{notice&&<div className="site-review-notice">{notice}</div>}<div className="site-review-layout"><section className="site-review-preview"><div className="site-review-preview-head"><strong>Vista previa del sitio</strong><span>Solo lectura</span></div><div className="site-review-frame"><iframe title="Vista previa del sitio para aprobación" srcDoc={preview}/></div></section><aside className="site-review-panel"><h2>Validar entrega</h2><p>Revisa el resultado antes de aprobarlo. La aprobación cambia el estado a listo para publicar.</p><section><h3>Cambios detectados</h3>{changed.length?<ul className="site-review-changes">{changed.map(item=><li key={item}>{item}</li>)}</ul>:<small>No se detectaron cambios respecto a la versión anterior.</small>}</section><details className="site-review-json"><summary>Ver configuración actual</summary><pre>{JSON.stringify(data.project.configuration,null,2)}</pre></details><section><h3>Historial de versiones</h3><div className="site-review-versions">{data.versions.length?data.versions.map(version=><div key={version.id}><strong>Versión {version.version}</strong><span>{new Date(version.created_at).toLocaleString("es-HN")}</span>{version.version===data.versions[0].version&&<em>Actual</em>}</div>):<small>Aún no hay versiones guardadas.</small>}</div></section>{data.project.review_note&&<section className="site-review-old-note"><h3>Observación anterior</h3><p>{data.project.review_note}</p></section>}{data.canReview&&data.project.status==="review"?<section className="site-review-decision"><h3>Decisión</h3><textarea value={reviewNote} onChange={event=>setReviewNote(event.target.value)} placeholder="Observaciones para el vendedor (obligatorias al devolver)"/><div><button className="site-review-reject" disabled={saving} onClick={()=>void review("reject")}>Devolver al vendedor</button><button className="site-review-approve" disabled={saving} onClick={()=>void review("approve")}>Aprobar sitio</button></div></section>:<div className="site-review-readonly">{data.project.status==="review"?"Tu rol puede consultar la revisión, pero solo Superadmin o Implementador pueden decidir.":"Este sitio no está pendiente de aprobación."}</div>}</aside></div></main>;
}
